---
- name: Replace convert-script.sh with Ansible
  hosts: all
  become: yes
  vars:
    inspirational_message: 'Greetings Earthlings! We come in peace!'

  tasks:
    - name: Install the latest version of Docker
      yum:
        name: docker
        state: latest

    - name: Copy myapp.service to /etc/systemd/system/myapp.service
      copy: 
        src: myapp.service
        dest: /etc/systemd/system/myapp.service
        owner: root
        group: root
        mode: 0700

    - name: Make sure myapp.service is enabled and running
      systemd:
        name: myapp
        enabled: yes
        state: started

    - name: Make sure docker is enabled and running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copy app files
      copy: 
        src: app
        dest: /tmp/build_app

    - name: build main.py from template
      template: 
        src: templates/mainpy.j2
        dest: /tmp/build_app/app/main.py

    - name: Build image from Dockerfile
      shell: docker build -t myapp .
      args:
        chdir: /tmp/build_app/app

    - name: Reload myapp
      systemd:
        name: myapp
        state: reloaded

    - debug:
        msg: Hello, world
