- name: create user accounts
  user:
    name: "{{ item }}"
  with_items: "{{ users }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  with_items: "{{ users }}"

- name: setup base machine based on ansbible facts
  import_tasks: docker.yml
  when: ansible_facts['container_tool']|lower == 'docker'
- import_tasks: foo.yml
  when: ansible_facts['foo']|lower == 'bar'